const Noto_Sans_KR = {
  thin: {
    weight: '100',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-thin',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  extraLight: {
    weight: '200',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-extraLight',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  light: {
    weight: '300',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-light',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  regular: {
    weight: '400',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-regular',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  medium: {
    weight: '500',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-medium',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  semiBold: {
    weight: '600',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-semiBold',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  bold: {
    weight: '700',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-bold',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  extraBold: {
    weight: '800',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-extraBold',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
  black: {
    weight: '900',
    style: 'normal',
    subsets: ['latin', 'korean'],
    variable: '--noto-sans_KR-black',
    fallback: [
      '-apple-system',
      'Malgun Gothic',
      'Apple SD Gothic Neo',
      'Roboto',
      'Apple Color Emoji',
      'Segoe UI Emoji',
      'Segoe UI Symbol',
      'sans-serif',
    ],
  },
};

export default Noto_Sans_KR;